In [1]:
from tqdm import trange, notebook

In [2]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline
import os 
from glob import glob
from PIL import Image

In [3]:
data_list = glob('./CIFAR100/train/*.png')

In [4]:
def get_label_from_path(path):
    labelpath1 = path.split('\\')[-1]
    labelpath2 = labelpath1.split('.')[-2]
    labelpath3 = labelpath2.split('_')[1:]
    labelpath4 = "_".join(labelpath3)
    return labelpath4

In [5]:
label_name_list = []
for path in data_list:
    label_name_list.append(get_label_from_path(path))

In [6]:
unique_label_names = np.unique(label_name_list)

In [7]:
print(unique_label_names, len(unique_label_names))

['apple' 'aquarium_fish' 'baby' 'bear' 'beaver' 'bed' 'bee' 'beetle'
 'bicycle' 'bottle' 'bowl' 'boy' 'bridge' 'bus' 'butterfly' 'camel' 'can'
 'castle' 'caterpillar' 'cattle' 'chair' 'chimpanzee' 'clock' 'cloud'
 'cockroach' 'couch' 'crab' 'crocodile' 'cup' 'dinosaur' 'dolphin'
 'elephant' 'flatfish' 'forest' 'fox' 'girl' 'hamster' 'house' 'kangaroo'
 'keyboard' 'lamp' 'lawn_mower' 'leopard' 'lion' 'lizard' 'lobster' 'man'
 'maple_tree' 'motorcycle' 'mountain' 'mouse' 'mushroom' 'oak_tree'
 'orange' 'orchid' 'otter' 'palm_tree' 'pear' 'pickup_truck' 'pine_tree'
 'plain' 'plate' 'poppy' 'porcupine' 'possum' 'rabbit' 'raccoon' 'ray'
 'road' 'rocket' 'rose' 'sea' 'seal' 'shark' 'shrew' 'skunk' 'skyscraper'
 'snail' 'snake' 'spider' 'squirrel' 'streetcar' 'sunflower'
 'sweet_pepper' 'table' 'tank' 'telephone' 'television' 'tiger' 'tractor'
 'train' 'trout' 'tulip' 'turtle' 'wardrobe' 'whale' 'willow_tree' 'wolf'
 'woman' 'worm'] 100


In [8]:
# label_name_array = np.array(label_name_list)
# train_y = []
# train_y.append(label_name_array)

In [9]:
# train_y

In [10]:
# train_y_1d = np.concatenate(train_y)

In [11]:
# train_y_1d

In [12]:
unique_label_num = []
a = 0
for temp in range(len(unique_label_names)):
    unique_label_num.append(a)
    a+=1

In [13]:
unique_label_num

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [14]:
unique_label_num_array = np.array(unique_label_num)

In [15]:
# label_name_array = np.array(label_name_list)
train_y_list = []
for label_name_index in range(len(label_name_list)):
    for unique_label_name_index in range(len(unique_label_names)):
        if (label_name_list[label_name_index] == unique_label_names[unique_label_name_index]):
            train_y_list.append(unique_label_name_index)
train_y = np.array(train_y_list)


In [16]:
train_y

array([19, 48, 77, ..., 96, 93, 31])

In [17]:
# unique_label_num = []
# a = 0
# for temp in range(len(unique_label_names)):
#     unique_label_num.append(a)
#     a+=1

In [18]:
# label_num = []
# for label_name_index in range(len(label_name_list)):
#     for unique_label_name_index in range(len(unique_label_names)):
#         if (label_name_list[label_name_index] == unique_label_names[unique_label_name_index]):
#             label_num.append(unique_label_name_index)
# print(label_num)

In [19]:
paths = tf.io.matching_files('./CIFAR100/train/*.png')

In [20]:
paths

<tf.Tensor: shape=(50000,), dtype=string, numpy=
array([b'.\\CIFAR100\\train\\0_cattle.png',
       b'.\\CIFAR100\\train\\10000_motorcycle.png',
       b'.\\CIFAR100\\train\\10001_snail.png', ...,
       b'.\\CIFAR100\\train\\999_willow_tree.png',
       b'.\\CIFAR100\\train\\99_turtle.png',
       b'.\\CIFAR100\\train\\9_elephant.png'], dtype=object)>

In [21]:
def tf_read_image(paths):
    gfile = tf.io.read_file(paths)
    image = tf.io.decode_image(gfile, dtype=tf.float32)
    return image

In [22]:
def make_batch(batch_paths):
    batch_images = []
    for paths in batch_paths:
        image = tf_read_image(path)
        batch_images.append(image)
    return tf.convert_to_tensor(batch_images)

In [23]:
train_x = make_batch(paths)

In [24]:
train_x.shape, train_y.shape

(TensorShape([50000, 32, 32, 3]), (50000,))

In [25]:
train_x.shape

TensorShape([50000, 32, 32, 3])

In [26]:
train_x

<tf.Tensor: shape=(50000, 32, 32, 3), dtype=float32, numpy=
array([[[[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [0.80784315, 0.80784315, 0.8039216 ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],

        [[1.        , 1.        , 1.        ],
         [0.99607843, 0.99607843, 0.99607843],
         [1.        , 1.        , 1.        ],
         ...,
         [0.8901961 , 0.8901961 , 0.88235295],
         [0.99607843, 0.99607843, 0.99607843],
         [1.        , 1.        , 1.        ]],

        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],

        ...,

        [[0.5686275 , 0.5254902 

In [27]:
test_path = tf.io.matching_files('./CIFAR100/test/*.png')

In [29]:
test_x = make_batch(test_path)

In [30]:
len(test_x)

10000

In [31]:
test_x.shape

TensorShape([10000, 32, 32, 3])

In [32]:
test_data_list = glob('./CIFAR100/test/*.png')

In [33]:
test_label_name_list = []
for path in test_data_list:
    test_label_name_list.append(get_label_from_path(path))

In [34]:
test_unique_label_names = np.unique(test_label_name_list)

In [35]:
print(test_unique_label_names, len(test_unique_label_names))

['apple' 'aquarium_fish' 'baby' 'bear' 'beaver' 'bed' 'bee' 'beetle'
 'bicycle' 'bottle' 'bowl' 'boy' 'bridge' 'bus' 'butterfly' 'camel' 'can'
 'castle' 'caterpillar' 'cattle' 'chair' 'chimpanzee' 'clock' 'cloud'
 'cockroach' 'couch' 'crab' 'crocodile' 'cup' 'dinosaur' 'dolphin'
 'elephant' 'flatfish' 'forest' 'fox' 'girl' 'hamster' 'house' 'kangaroo'
 'keyboard' 'lamp' 'lawn_mower' 'leopard' 'lion' 'lizard' 'lobster' 'man'
 'maple_tree' 'motorcycle' 'mountain' 'mouse' 'mushroom' 'oak_tree'
 'orange' 'orchid' 'otter' 'palm_tree' 'pear' 'pickup_truck' 'pine_tree'
 'plain' 'plate' 'poppy' 'porcupine' 'possum' 'rabbit' 'raccoon' 'ray'
 'road' 'rocket' 'rose' 'sea' 'seal' 'shark' 'shrew' 'skunk' 'skyscraper'
 'snail' 'snake' 'spider' 'squirrel' 'streetcar' 'sunflower'
 'sweet_pepper' 'table' 'tank' 'telephone' 'television' 'tiger' 'tractor'
 'train' 'trout' 'tulip' 'turtle' 'wardrobe' 'whale' 'willow_tree' 'wolf'
 'woman' 'worm'] 100


In [36]:
len(test_label_name_list)

10000

In [37]:
test_unique_label_num = []
a = 0
for temp in range(len(test_unique_label_names)):
    test_unique_label_num.append(a)
    a+=1

In [38]:
test_unique_label_names = np.unique(test_label_name_list)

In [39]:
test_y_list = []
for test_label_name_index in range(len(test_label_name_list)):
    for test_unique_label_name_index in range(len(test_unique_label_names)):
        if (test_label_name_list[test_label_name_index] == test_unique_label_names[test_unique_label_name_index]):
            test_y_list.append(test_unique_label_name_index)
test_y = np.array(test_y_list)

In [40]:
test_x, test_x.shape

(<tf.Tensor: shape=(10000, 32, 32, 3), dtype=float32, numpy=
 array([[[[1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ],
          ...,
          [0.80784315, 0.80784315, 0.8039216 ],
          [1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ]],
 
         [[1.        , 1.        , 1.        ],
          [0.99607843, 0.99607843, 0.99607843],
          [1.        , 1.        , 1.        ],
          ...,
          [0.8901961 , 0.8901961 , 0.88235295],
          [0.99607843, 0.99607843, 0.99607843],
          [1.        , 1.        , 1.        ]],
 
         [[1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ],
          ...,
          [1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ],
          [1.        , 1.        , 1.        ]],
 
         ...,
 
     

In [41]:
test_y, test_y.shape

(array([49, 65, 67, ..., 91, 35,  0]), (10000,))

In [43]:
input_shape = (32,32,3)
num_classes = 100

In [ ]:
# test_label_name_array = np.array(test_label_name_list)
# test_y = []
# test_y.append(test_label_name_array)

In [ ]:
# test_y_1d = np.concatenate(test_y)

In [ ]:
# test_x.shape, test_y_1d.shape

In [44]:
def Mymodel(input_shape, num_classes):
    
    myinput = tf.keras.layers.Input(shape=input_shape)
    
    net= tf.keras.layers.Conv2D(32,3,1,padding='same',activation='relu')(myinput)
    net= tf.keras.layers.Conv2D(32,3,1,padding='same',activation='relu')(net)
    net = tf.keras.layers.MaxPool2D(pool_size=(2,2))(net)
    net = tf.keras.layers.Dropout(0.2)(net)
    
    net= tf.keras.layers.Conv2D(64,3,1,padding='same',activation='relu')(myinput)
    net= tf.keras.layers.Conv2D(64,3,1,padding='same',activation='relu')(net)
    net = tf.keras.layers.MaxPool2D(pool_size=(2,2))(net)
    net = tf.keras.layers.Dropout(0.2)(net)
    
    net= tf.keras.layers.Flatten()(net)
    net= tf.keras.layers.Dense(512, activation='relu')(net)
    net = tf.keras.layers.Dropout(0.3)(net)
    net = tf.keras.layers.Dense(num_classes,activation='softmax')(net)
    
    model = tf.keras.Model(inputs=myinput, outputs=net, name="TEST")
    return model

In [45]:
model = Mymodel(input_shape, num_classes)

In [46]:
model.summary()

Model: "TEST"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 32, 32, 3)]       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 32, 64)        1792      
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 32, 32, 64)        36928     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 16, 16, 64)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 16, 16, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 16384)             0         
_________________________________________________________________
dense (Dense)                (None, 512)               8389120

In [47]:
model.compile(optimizer=tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [48]:
num_epochs = 5
b_size = 32
hist = model.fit(train_x, train_y, validation_data=(test_x,test_y), batch_size=b_size, shuffle= True,epochs=num_epochs)

Epoch 1/5
 193/1563 [==>...........................] - ETA: 2:20 - loss: 4.6098 - accuracy: 0.0076

KeyboardInterrupt: 

In [ ]:
# def myResize(input_imgs, dst_size):
#     out_imgs = []
#     for img in input_imgs:
#         img_out = cv2.resize(img,dsize=(dst_size,dst_size),interpolation=cv2.INTER_LINEAR)
#         img_out = cv2.merge([img_out, img_out, img_out])
#         out_imgs.append(img_out)
#     return np.array(out_imgs)